
return {
    "common.libs.ui.ui_help",
    "common.libs.ui.ui_panel.ui_panel_def",
    "common.libs.ui.ui_panel.ui_panel_event",
    "common.libs.ui.ui_panel.ui_panel_base",
    "common.libs.ui.ui_panel.ui_panel_mgr",
    "common.libs.ui.ui_component.ui_component",
    "common.libs.ui.ui_component.ui_text",
    "common.libs.ui.ui_component.ui_image",
    "common.libs.ui.ui_component.ui_button",
    "common.init_common_global_vars",

    "app.game_state.app_state.app_state_def",
    "app.game_state.app_state.app_state_mgr",
    "app.game_state.app_state.app_state_base",
    "app.game_state.app_state.app_composite_state_base",
    "app.game_state.app_state.app_state_exit_game",
    "app.game_state.app_state.app_state_in_game",
    "app.game_state.app_state.app_state_init_game",
    "app.game_state.app_state.app_state_wait_task",

    "app.game_state.in_game_state.in_game_state_def",
    "app.game_state.in_game_state.in_game_state_base",
    "app.game_state.in_game_state.in_game_state_mgr",
    "app.game_state.in_game_state.in_game_state_enter",
    "app.game_state.in_game_state.in_game_state_exit",
    "app.game_state.in_game_state.in_game_state_login",
    "app.game_state.in_game_state.in_game_state_logout",
    "app.game_state.in_game_state.in_game_state_run",
    "app.game_state.in_game_state.in_game_state_launch_role",

    "app.ui.main_panel.ui_main_panel",
    "app.ui.login_panel.ui_login_panel",
    "app.ui.launch_role_panel.launch_role_panel",
    "app.ui.ui_panel_setting",

    "app.logic.role.role",
    "app.logic.role.main_role",
    "app.logic.role.role_mgr",
    "app.logic.user.main_user",

    "app.net.net_mgr",
    "app.net.cnn_logic_base",
    "app.net.gate_cnn_logic",
    "app.net.login_cnn_logic",
    "app.net.fight_cnn_logic",

    "app.data.data_mgr",
}