local files = {
    "libs.serpent",
    "libs.print_ext",
    "libs.class",
    "libs.math_ext",
    "libs.string_ext",
    "libs.table_ext",
    "libs.type_check",
    "libs.assert",
    "libs.path_ext",
    "libs.xml2lua.xml2lua_ext",
    "rapidjson",
    "pb",
    "lpeg",
    "tryuselualib",
    "lfs",
    "common.net.net_handler",
    "common.net.tcp_connect",
    "common.net.tcp_listen",
}
return files