
if(WIN32)
  set_property(GLOBAL PROPERTY USE_FOLDERS On)
  add_definitions(/wd4996)
  ADD_DEFINITIONS(/D _CRT_SECURE_NO_WARNINGS /wd4267 /wd4244 /wd4996 /wd4800 /D _WINSOCK_DEPRECATED_NO_WARNINGS)
endif(WIN32)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

#MESSAGE(STATUS ${CMAKE_BINARY_DIR})
#MESSAGE(STATUS ${CMAKE_SOURCE_DIR})
#MESSAGE(STATUS ${PROJECT_BINARY_DIR})
#MESSAGE(STATUS ${PROJECT_SOURCE_DIR})